### PR TITLE
Sponsors Section Updated and Past Glimpse images added

### PR DESCRIPTION
**Pull request by eshaan007**
6 Sponsors Added instead of 4
Sponsors

### CODE REVIEW

**Comment by eshaan007** [comment]
pastYearGlimpses

**Comment by eshaan007** [comment]
http://ishaan.surge.sh/

<blockquote><div><strong><a href="http://ishaan.surge.sh/">Cerebro</a></strong></div><div>Naya cerebro</div></blockquote>

**Comment by thepushkarp** [comment]
Addresses issue #52

**Comment by eshaan007** [comment]
MobileView

Past Glimpses : Mobile View Updated

**Comment by eshaan007** [comment]
MobileView

Past Glimpses : Mobile View Updated

**Comment by rossoskull** [comment]
Resolve the conflicts @eshaan007

**Review by rossoskull — APPROVED** [review]

**Pull request merged**
