### PR TITLE
Events WIP

### PR DESCRIPTION
**Pull request by anujpuri72**

### CODE REVIEW

**Comment by pAditya198** [comment]
http://cerebro20.surge.sh/

<blockquote><div><strong><a href="http://cerebro20.surge.sh/">Cerebro</a></strong></div><div>Naya cerebro</div></blockquote>

**Comment by pAditya198** [comment]
this surge link will be updated as we progress

**Comment by rossoskull** [comment]
Resolve the conflicts

**Comment by anujpuri72** [comment]
@rossoskull conflicts resolved

**Pull request closed without merging**
