### PR TITLE
Google login 

### PR DESCRIPTION
**Pull request by AmanRaj1608**

### CODE REVIEW

**Review by samagragupta — COMMENTED** [review]
conflicts?

**Comment by AmanRaj1608** [comment]
@samagragupta @rossoskull  updated

storing user object in local storage with password as access_token 

And storing user name and email in state.
  

image

**Comment by rossoskull** [comment]
@AmanRaj1608 don't store password, store the accessToken, email Id, first name, last name and profile picture

**Comment by AmanRaj1608** [comment]
@rossoskull fixed.

image

**Comment by singhpratyush** [comment]
- Better to store access token as a cookie.
- Pay attention to linting. Why `access_token` when you can `accessToken` (this seems to be the convention for the project).

**Comment by AmanRaj1608** [comment]
@singhpratyush 

**Made the changes. I will take care of the proper linting next time.
Still curious why use cookie and not localStorage. Cookies can be transferred to third parties.**

**Review by rossoskull — APPROVED** [review]

**Pull request merged**
