### PR TITLE
Made Cover Responsive

### PR DESCRIPTION
**Pull request by MayankAjmeri**
Made the timer and astronaut responsive. Added overflow hidden to outer containers of all components.
Screenshot (20)

### CODE REVIEW

**Comment by rossoskull** [comment]
Provide a surge link

**Comment by MayankAjmeri** [comment]
cerebro_temp.surge.sh

**Comment by MayankAjmeri** [comment]
http://cerebro_temp.surge.sh/

**Review by samagragupta — COMMENTED** [review]
Resolve the conflicts.

**Review by samagragupta — COMMENTED** [review]
In the mobile view, instead of `Techfest IIIT Vadodara`, date is written.
Check out the design.

**Pull request merged**
